#!/bin/bash

while [[ $# -gt 0 ]]
do
	opt="$1"
	case $opt in 
		-f|--file)
			file="$2"
			shift
		;;
		-V|--view)
			view=1
		;;
		-S|--set)
			set=1
		;;
		-c|--comments)
			comments=1
		;;
		-h|--help)
			echo -e "\npINI v0.8\tWritten by Bryce McNab\n\npINI (parse INI) is an ini parser written in bash.\n\n\t-f|--file\tSpecify the ini file to parse.\n\t-V|--view\tDisplay the ini contents in a table\n\t-S|--set\tSets all the settings in the configurations files as variables.\n\t-c|--comments\tDisplays all comments in the .ini file.\n\t-h|--help\tDisplays this page.\n\n\tSections: ini files can contain \[sections\]. These are parsed as arrays with key=value set as an element.\n\nNOTE: pINI is written for Bash 3.2.57 at the moment.\n"
		;;
	esac
	shift
done

bashVersion=$(echo ${BASH_VERSION%%[^0-9.]*} | grep -o ^[0-9]*)
if [[ $bashVersion == 3 ]]
then
	echo -e "\n!!! Warning: running in bash \"$BASH_VERSION\". The -S feature will not set sectioned variables into associative arrays. !!!\n" 
fi

## View ini file in a column format
if [[ $view == 1 ]]
then
	(echo -e "key=value\n----=----" && cat $file | grep -v "^;" | grep -v "^\[") | column -t -s "="
fi

## Set variables in ini files: use ". ./pini" to set variables in the current shell. 
if [[ $set == 1 ]]
then
	while read line
	do
		key=$(echo $line | awk -F "=" '{ print $1 }')
		commentOrNot=$(echo $key | grep -o "^\;")
		value=$(echo $line | awk -F "=" '{ print $2 }')
		
		if [[ $key =~ ^\[.*$ ]]
		then
			section=$(echo $key | sed "s/\[//g" | sed "s/\]//g")
			eval unset "${section}"
			if [[ $bashVersion == 3 ]]
			then
				declare -a "${section}"
			elif [[ $bashVersion == 4 ]]
			then
				declare -A "${section}"
			fi
		elif [[ ( "$key" != "" ) && ( "$commentOrNot" != ";" ) ]]
		then
			if [[ "$section" == "" ]]
			then
				declare "${key}"="${value}"
			else
				if [[ $bashVersion == 3 ]]
				then
					element=$(eval echo \${#$section[@]})
					eval $section[$element]="${key}=\"${value}\""
				elif [[ $bashVersion == 4 ]]
				then
					read "$section[$key]" <<< "$value"
				fi
			fi
		fi
	done < $file
fi

## View comments
if [[ $comments == 1 ]]
then
	while read line
	do
		echo $line | grep "^;"
	done < $file
fi

# Clean variables
unset file view set comments section key value
